@startuml
'https://plantuml.com/class-diagram


Package Controller
{
    class Facade
    {
        -String player1
        -String player2
    }
}
Package model
{
    interface EchecObserver
    {
            +updateMouvementPossible()
            +updateMouvement()
            +updateEchec()
    }

    class Echec {
    +FintourJoueur(color Color)
    +mouvement(position Integer[])
    -verifEchec(color Color) : Boolean
    -verifEchecMath(color Color) : Boolean
    +setPiece(piece Piece x int y int)
    +creationPartie()
    }
    class pieceFactory
    {
        +PieceFactory()
        +createPion() : piece Piece
        +createCavalier() : piece Piece
        +createFou() : piece Piece
        +createTour() : piece Piece
        +createDame() : piece Piece
        +createRoi() : piece Piece
    }
    abstract class Piece
    {
        +mouvementPossibles Integer[]
        +getColor()
        +capturePiece()
    }
    class Pion extends Piece
    {
        -boolean tour1
        +{static}Pion(color Color)
        +promotion()
        +CalculmouvementPossible(echec Echec) : Integer[][]
    }
    class Cavalier extends Piece
    {
    +{static}Cavalier(color Color)
    +CalculmouvementPossible(echec Echec) : Integer[]
    }
    class Fou extends Piece
    {
    +{static}Fou(color Color)
    +CalculmouvementPossible(echec Echec) : Integer[]
    }
    class Tour extends Piece
    {
    +{static}Tour(color Color)
    +CalculmouvementPossible(echec Echec) : Integer[]
    }
    class Dame extends Piece
    {
    +{static}Dame(color Color)
    +CalculmouvementPossible(echec Echec) : Integer[]
    }
    class Roi extends Piece
    {
    +{static}Roi(color Color)
    +CalculmouvementPossible(echec Echec) : Integer[]
    }
    Enum Color
    {
        WHITE
        BLACK
    }
}
Package view{

    class EchecWindow implements EchecObserver
    {
     +EchecWindow()
     +gameStart()
     +GameFinish()
    }

}
Piece *--> "1\n- color" Color : > A pour couleur
Echec *--> "-64" Piece : > A besoin

Echec ..> pieceFactory : > <<use>>

pieceFactory ...> Piece : > <<use>>
pieceFactory ..> Roi : > <<use>>
pieceFactory ..> Pion : > <<use>>
pieceFactory ..> Cavalier : > <<use>>
pieceFactory ..> Fou : > <<use>>
pieceFactory ..> Dame : > <<use>>
pieceFactory ..> Tour : > <<use>>


EchecObserver <--o Echec : > Consult
Facade --> Echec : > Manipule
Facade ..> EchecWindow : > Selectionne
EchecWindow --> Facade : > Transmet_Demandes

@enduml